### ISSUE TITLE
Problems installing GribMagic

### ISSUE THREAD

**Issue by Linuxuser1234** [earthobservations/gribmagic#20]
Hi. When i run the file i keep getting invalid syntax when i run `python setup.py install`.

**Comment by amotl** [comment]
Dear @awipslinuxuser,

thanks for writing in. I just verified it works when aiming for a development sandbox [1]:
```
git clone https://github.com/earthobservations/gribmagic.git
cd gribmagic
python3 -m venv .venv
source .venv/bin/activate
python setup.py develop

python -V
Python 3.9.7

gribmagic --help

Commands:
  dwd      DWD GRIB data downloader.
  install  Install helper programs.
  smith    Toolsmith.
  unity    Unified NWP data downloader.
```

For a regular installation, you might just want to use `pip`, like:
```
python3 -m venv .venv
source .venv/bin/activate
pip install gribmagic --upgrade
```

Let me know if you still observe any problems. If so, please share a more detailed error message.

With kind regards,
Andreas.

[1] There is also a section in the documentation about the development sandbox, see https://github.com/earthobservations/gribmagic/#development.

**Comment by awipslinuxuser** [comment]
@amotl  i got it installed is there a gui window??

**Comment by amotl** [comment]
All right. This program does not have a GUI, please use the CLI.

**Comment by Linuxuser1234** [comment]
@amotl  the one script i cant run is in the demo folder that is magics.py it keeps saying
```python
Traceback (most recent call last):
  File "magics.py", line 4, in <module>
    from magics import macro as magics
  File "/home/kali/Desktop/gribmagic-main/demo/magics.py", line 4, in <module>
    from magics import macro as magics
ImportError: cannot import name macro
```

**Comment by amotl** [comment]
Dear @awipslinuxuser,

thanks for sharing the traceback. This essentially means that the [Magics](https://confluence.ecmwf.int/display/MAGP/) program and/or its Python bindings are not installed on your machine. There is some documentation about this at the section about the `bbox` tool, see [1]. YMMV.

In the best case, to get it running, you would invoke something along the lines of
```
apt-get install --yes libmagplus3v5
pip install gribmagic[plotting]
```

and then run the `gribmagic` program [2].

With kind regards,
Andreas.

[1] https://github.com/earthobservations/gribmagic#run-bbox-tool
[2] The main subsystems available from this package are exposed via the `gribmagic` program entrypoint, this is probably the CLI interface you might want to use. All programs in the `demo` folder are actually just scribbles, I probably should rename this folder to `spikes`.

**Comment by Linuxuser1234** [comment]
ok thats what i didn't do ok because i did install macro also I'm developing a software for weather radar on python if you want to help
